### ISSUE TITLE
feat/orm does not typecheck: #102 made `detail` required and one call site was missed

### ISSUE THREAD

**Issue by nstfkc** [nstfkc/gemi#159]
`feat/orm` at 279778a fails `tsc`:

```
orm/compile/group-by.ts(674,11): error TS2554: Expected 4 arguments, but got 3.
```

Verified on a clean checkout of `origin/feat/orm`, not on a working branch.

## How it got there

A semantic merge conflict — the kind neither PR can see.

- **#92** added `throw new UnsupportedQueryError(key, schema.name, op)` in `groupBy`'s `assertArgs`, when `detail` was optional.
- **#102** made `detail` **required** — the second half of #61 — and fixed the call sites on its own branch.

Each typechecked alone. `group-by.ts` was not touched by #102 and `errors.ts` was not touched by #92, so there was no textual conflict to resolve and no diff for either reviewer to look at. The break exists only in the combination.

## Why it matters beyond the error

Every branch stacked on `feat/orm` inherits it, so `tsc` is now failing for reasons unrelated to whatever a contributor is working on — which is exactly the condition under which people start ignoring it.

I found it while merging `feat/orm` into #103 to clear that PR's conflict: the merge produced one `tsc` error, and both files involved turned out byte-identical to `feat/orm`.

## The fix

Supply the detail, in the wording `read.ts` already uses for the same refusal:

```ts
`${op} takes ${[...GROUP_BY_ARGS].sort().join(", ")}.`
```

That is the case #61's second half was actually about — an argument the operation does not accept is the path a typo arrives on, and naming the set is the whole of the answer.

## Acceptance

- `tsc` clean on `feat/orm`.
- A test on the **message**, not only the signature. `tsc` catches the arity; nothing would have caught a `detail` that said nothing useful, which is the failure #102 set out to prevent.

**Comment by nstfkc** [comment]
Resolved by #160, merged into `feat/orm`. Closing by hand — GitHub only auto-closes on merges to the default branch.
