### ISSUE TITLE
Redirect props collapse to { action } after Link became overloaded in 0.63.0

### ISSUE THREAD

**Issue by nstfkc** [nstfkc/gemi#584]
## Problem

In 0.63.0, `Link` changed from a single generic component to an overloaded `LinkComponent` type (`ExternalLinkProps` for an `AbsoluteUrl`, and `LinkProps<T>` for a route path). `Redirect` still takes its props from that type:

```ts
// dist/client/Redirect.d.ts
export declare const Redirect: (props: ComponentProps<typeof Link> & {
    action: "push" | "replace";
}) => JSX.Element;
```

`ComponentProps` can't resolve props from an overloaded, generic call signature, so `ComponentProps<typeof Link>` comes out empty. As a result, `Redirect` accepts only `action`, and every `href`/`params` passed to it fails type-check.

## Repro

```tsx
import { Redirect } from "gemi/client";

<Redirect action="replace" href="/app/redirect" />;
// TS2322: Type '{ action: "replace"; href: string; }' is not assignable to
// type 'IntrinsicAttributes & { action: "push" | "replace"; }'.
```

The same thing happens in app code that derives a type from `Link`, for example `ComponentProps<typeof Link>["href"]` → `Property 'href' does not exist on type '{}'`.

Worked in 0.63.0-rc.1, where `Link` was `MemoExoticComponent<<T extends keyof Views>(props: LinkProps<T>) => JSX.Element>`.

## Suggested fix

- Export `LinkProps` (and the external variant) from `gemi/client`.
- Type `Redirect` against them directly, e.g. `<T extends keyof Views>(props: LinkProps<T> & { action: "push" | "replace" })`, instead of `ComponentProps<typeof Link>`.

This lets apps derive `href` types from an exported type instead of `ComponentProps<typeof Link>`.

## Impact

Blocks upgrading Folio from 0.63.0-rc.1 to 0.63.0: 8 type errors, across 4 `<Redirect>` call sites and 3 `BackHref`-style derived types.
